#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
export VISUAL="code --wait"
export EDITOR="$VISUAL"
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Alias to source quesmed scripts
alias source_quesmed="source /Volumes/JinalData/Projects/quesmed/quesmed-scripts/local_helper.sh"
alias edit_prezto="code ~/.zprezto/ ~/.zprezto/runcoms/zshrc"
function iterm() {
  open -a iTerm .
}

# Load pyenv automatically by appending
if [[ $USE_PYENV == 1 ]]; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
else
  alias python="/usr/bin/env python3"
  alias pip="/usr/bin/env pip3"
fi

# Customize to your needs...
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/custom/transfer.sh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/custom/transfer.sh"
fi
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc' ]; then source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc' ]; then source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'; fi
# export PATH="/usr/local/opt/node@8/bin:$PATH"
